# ================================================================================================ #
# Description: Runs the analysis comparing the treated & control / before & after populations
# to produce output for submission to checking as part of the outcomes-framework social housing test case 
# (paper 5). The analysis mainly consists of cross tabs for the sample means and sd for comparing the 
# Before-After populations. There are 3 components to the analysis - 
#   1. Main analysis that compares the group that was housed 12 months before GSS interview to the group housed 
#       15 months after.
#   2. Validation of main analysis comparing the group that was housed 12 months before GSS interview to the 
#       group housed 12 months after
#   3. Validation of main analysis comparing the group that was housed 12 months before GSS interview to the 
#       group housed 15 months after, but after applying a weighting to this group using propensity scores.
#
# Input: 
#
# Output: Comma separated text files suitable for opening in Excel, containing all the prepared output
# and ready for confidentialization. Also, plots of all the cross-tables (with an option to save these)
# for ease of visualization.
# 
# Author: S. Anastasiadis
#
# Dependencies:
# SIAtoolbox - for reading SQL database
# data_loading_and_preparation.R - for data preparation
# function_for_treat_control.R - for data analysis
#
# Notes: Run-time is approx 4 minutes
#
# History (reverse order): 
# 28 Nov 2017 SA v1
# 13 Sep 2018 BV Reorganised code, added comments
# 01 Dec 2018 BV Adapted for Social Housing 3 (tabs, t-test and regressions and main group and sensitivity only)
# ================================================================================================ #

library(SIAtoolbox)
library(RODBC)
library(ggplot2)
library(Matching)
library(dplyr)
library(reshape2)
library(weights)
library(robustbase)
library(xlsx)
library(stringr)

# set working directory
setwd("~/Network-Shares/DataLabNas/MAA/MAA2016-15 Supporting the Social Investment Unit/outcomes_framework/sh3/rprogs/analytics_social_housing_3/")

# start time
print("Start time:")
print(Sys.time())

################ Parameters ################
# Number of repetitions needed for doing bootstrap sampling that's used in the generation of confidence intervals
NUM_REPS <- 400
# Decide whether the plots generated by the analysis is to be saved for later reference
SAVE_PLOTS <- TRUE

# DB name
databasename <- "IDI_Clean_20181020"
sandpitname <-"[DL-MAA2016-15]"

################ Source ################

# functions
source('./function_for_treat_control.R')
# data preparation
source('./data_loading_and_preparation.R')


################ analysis when dependent variable = treat_control_main ################
# runs the analysis against the explanotory variables:

# for the treatment/control "main" groups = new applications and gss_itw to housed between -12 and 15 months
dependent_var <- "treat_control_main"

# crosstabs (+ CI by bootstrap) + plots + t-test betweeen the 2 groups
analysis_wrapper(dataset, dependent_var, SAVE_PLOTS, columns_to_analyse)




# robust regressions / hh_gss_income_median WITH income---------------------------------------------------
reg_formulas <- cbind(
          # formulas for the regressions
          c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
          ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
          ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
          ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
          ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
          ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
          ),
          # regression family (binomial / gaussian)
          c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
          )

robust_glm_wrapper(reg_formulas, dataset, dependent_var, suffix = "_hh_gss_income_median_with_income")
#glm_wrapper(reg_formulas, dataset, dependent_var)

# for hnz_prim in the gss hhld
robust_glm_wrapper(reg_formulas, dataset[dataset$hnz_prim==1,], dependent_var, suffix="_hnz_prim_with_income")

# robust regressions / hh_gss_income_median without income---------------------------------------------------
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"
  ),
  # regression family (binomial / gaussian)
  c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
)

robust_glm_wrapper(reg_formulas, dataset, dependent_var, "_hh_gss_income_median_without_income")
#glm_wrapper(reg_formulas, dataset, dependent_var)

# for hnz_prim in the gss hhld
robust_glm_wrapper(reg_formulas, dataset[dataset$hnz_prim==1,], dependent_var, suffix="_hnz_prim_without_income")



# robust regressions / hh_gss_equi_income_median_inf ---------------------------------------------------
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_equi_income_median_inf+1) + treat_control_main + wave"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_equi_income_median_inf+1) + treat_control_main + wave"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_equi_income_median_inf+1) + treat_control_main + wave"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_equi_income_median_inf+1) + treat_control_main + wave"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_equi_income_median_inf+1) + treat_control_main + wave"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_equi_income_median_inf+1) + treat_control_main + wave"
  ),
  # regression family (binomial / gaussian)
  c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
)

robust_glm_wrapper(reg_formulas, dataset, dependent_var, "_hh_gss_eq_inc")
#glm_wrapper(reg_formulas, dataset, dependent_var)

# robust regressions / hh_gss_income_median + time_to_housed --------------------------------
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave + time_to_housed"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave + time_to_housed"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave + time_to_housed"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave + time_to_housed"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main +  wave + time_to_housed"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave + time_to_housed"
  ),
  # regression family (binomial / gaussian)
  c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
)

robust_glm_wrapper(reg_formulas, dataset, dependent_var, suffix="_time_housed")

# robust regressions / hh_gss_income_median + time_before_housed for control--------------------------------
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + wave + time_before_housed"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + wave  + time_before_housed"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + wave  + time_before_housed"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + wave + time_before_housed"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) +  wave  + time_before_housed"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + time_before_housed"
  ),
  # regression family (binomial / gaussian)
  c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
)

robust_glm_wrapper(reg_formulas, dataset[dataset$treat_control_main=='CONTROL',], dependent_var, suffix="_control")

# robust regressions / hh_equi_income_net_b4 ---------------------------------------
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_equi_income_net_b4+1) + treat_control_main + wave"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_equi_income_net_b4+1) + treat_control_main + wave"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_equi_income_net_b4+1) + treat_control_main + wave"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_equi_income_net_b4+1) + treat_control_main + wave"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_equi_income_net_b4+1) + treat_control_main + wave"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_equi_income_net_b4+1) + treat_control_main + wave"),
  # regression family (binomial / gaussian)
  c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
)

robust_glm_wrapper(reg_formulas, dataset, dependent_var, suffix="_adm_eq_inc")

# admin eq income regression
glm <- glm(as.formula("hh_equi_income_net_b4 ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"), data = dataset, family =  "gaussian") #, weights=wgt)
# lm.test <- lm(as.formula("hh_equi_income_net_b4 ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + treat_control_main + wave"), data = dataset) #, weights=wgt)
# lm()
print(summary(glm))
# print(summary(lm.test))

################ analysis when dependent variable = treat_control_sen ################
# runs the analysis against the explanotory variables:

# for the treatment/control "sensitivity" groups = new applications and gss_itw to housed between -12 and 12 months
dependent_var <- "treat_control_sen"

# crosstabs (+ CI by bootstrap) + plots + t-test betweeen the 2 groups
analysis_wrapper(dataset, dependent_var, SAVE_PLOTS, columns_to_analyse)


# robust regressions
reg_formulas <- cbind(
  # formulas for the regressions
  c("life_satisfaction_bin ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
    ,"life_satisfaction_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
    ,"gss_pq_house_mold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
    ,"gss_pq_house_cold_code ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
    ,"house_crowding_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
    ,"safety_ind ~ as_at_age + age2 + snz_sex_code + eth_maori + eth_pacifica + log(hh_gss_income_median+1) + treat_control_main + wave"
  ),
  # regression family (binomial / gaussian)
  c("binomial", "gaussian", "binomial", "binomial", "binomial", "binomial")
)

robust_glm_wrapper(reg_formulas, dataset, dependent_var)

